---
AllCops:
  Exclude:
    - spec/fixtures/**/*
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Style
Style/TrailingCommaInArguments:
  Description: Prefer always trailing comma on multiline argument lists. This makes
    diffs, and re-ordering nicer.
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  Description: Prefer always trailing comma on multiline literals. This makes diffs,
    and re-ordering nicer.
  EnforcedStyleForMultiline: comma
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets
Style/MethodMissing:
  Description: We use method_missing for all unrecognizable patterns in Puppetfile.
  Enabled: false

# Layout
Layout/ClosingParenthesisIndentation:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 300
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 140
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 15
