---
AllCops:
  Exclude:
    - spec/fixtures/**/*
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Style
Style/ConditionalAssignment:
  Description: This looks way more readable.
  EnforcedStyle: assign_inside_condition
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodMissingSuper:
  Description: We use method_missing for all unrecognizable patterns in Puppetfile.
  Enabled: false
Style/NumericLiterals:
  Description: Counter-intuitive for port numbers.
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/SpecialGlobalVars:
  Description: These look kinda scary.
  Enabled: false
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets
Style/FormatStringToken:
  Description: Hiera doesn't like this restriction.
  Enabled: false

# Layout
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Metrics
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 200
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
...
