---
sudo: false
language: ruby

rvm:
  - 2.3.5
  - 2.4.6
  - 2.5.4
  - 2.6.1
  - 2.7.0-preview1

stages:
  - rubocop
  - test

jobs:
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
...
