sudo: false
language: ruby
rvm:
  - 2.3.5
  - 2.4.2
  - 2.5.0

script: bundle exec rake $RAKE_TASK

jobs:
  include:
    - stage: rubocop
      env:
        - RAKE_TASK=rubocop
    - stage: test
      env:
        - RAKE_TASK=spec

