mod 'accounts',
  :hg  => 'https://hg.mycompany.net/puppet/accounts',
  :tag => '0.8.0'
mod 'nginx',
  git: 'https://github.com/voxpupuli/puppet/nginx',
  tag: 'v0.7.1'
mod 'stdlib',
  git:    'https://github.com/pegasd/puppetlabs-stdlib',
  branch: 'weird_fix'
mod 'monitoring',
  hg:        'https://hg.mycompany.net/puppet/monitoring',
  changeset: '19ab6af'
