mod 'accounts',
  :hg  => 'https://hg.mycompany.net/puppet/accounts',
  :tag => '0.8.0'
mod 'nginx',
  git: 'https://github.com/voxpupuli/puppet/nginx',
  tag: 'v0.7.1'
mod 'stdlib',
  git:    'https://github.com/pegasd/puppetlabs-stdlib',
  branch: 'weird_fix'
mod 'monitoring',
  hg:        'https://hg.mycompany.net/puppet/monitoring',
  changeset: '19ab6af'
mod 'logging',
  hg:  'https://hg.mycompany.net/puppet/logging',
  tag: '0.13.0'
mod 'puppetlabs/apt', '4.5.0'
mod 'puppetlabs/lvm', '0.9.0'
mod 'ntp', :git => 'https://github.com/puppetlabs/puppetlabs-ntp', :tag => '7.1.0-dev1'
mod 'docker', :git => 'https://github.com/puppetlabs/puppetlabs-docker', :tag => '1.0.3'
