mod 'config', :local
mod 'puppetlabs/stdlib', '4.19.0'
mod 'accounts',
  :hg  => 'https://hg.mycompany.net/puppet/accounts',
  :tag => '0.8.0'
mod 'nginx',
  git: 'https://github.com/voxpupuli/puppet-nginx',
  tag: :latest
mod 'apache',
  hg: 'https://hg.mycompany.net/puppet/apache',
  branch: 'crazy_fix'
mod 'mcollective',
  git: 'https://github.com/voxpupuli/puppet-mcollective',
  branch: 'puppet3'
